<?php
# 
# This file is part of Roundcube "detach_attachments" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 
$labels=array();
$labels['pluginname']='Große Dateianhänge';
$labels['plugindescription']='Für große Dateianhänge einen Download-Link versenden.';
$labels['expires']='Download verfällt am';
$labels['deleteconfirmation']='Wenn Sie fortfahren, wird der Anhang endgültig geschlöscht.';
$labels['downloadquestion']='Möchten Sie den Anhang vor dem Löschen herunterladen?';
$labels['deletelink']='Anhang vom Server löschen';
$labels['downloads']='Download<small>(s)</small>';
$labels['hint']='Sie sehen hier, wie oft der Anhang heruntergeladen wurde.<br />Wenn Sie den Anhang versehentlich versandt haben, dann löschen Sie ihn, um weitere Downloads zu verhindern.';
$labels['storeattachments']='Anhänge auf dem Server belassen';
$labels['cumsize']='Gesamtgröße der Anhänge';
$labels['filenotfound']='Die Datei konnte nicht gefunden werden.';