<?php
# 
# This file is part of Roundcube "detach_attachments" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Separar archivos adjuntos';
$labels['plugindescription']='Separa archivos adjuntos y envia un enlace de descarga en su lugar. Tenga en cuenta: los enlaces de descarga de los archivos adjuntos tienen una fecha de caducidad de 30 días.';
$labels['expires']='Descarga expira';
$labels['deleteconfirmation']='Si continúa el archivo adjunto se elimina del servidor de forma permanente. ¿Desea continuar?';
$labels['downloadquestion']='¿Desea descargar el archivo adjunto antes de eliminarlo?';
$labels['deletelink']='Borrar archivo adjunto de servidor';
$labels['downloads']='descarga(s)';
$labels['hint']='El número de descargas indica cuantas veces archivos adjuntos han sido descargados. Si archivos adjuntos son enviados por error, por favor elimínelos para prevenir descargas adicionales.';
$labels['storeattachments']='Mantener los archivos adjuntos en el servidor';
$labels['cumsize']='tamaño total de archivos adjuntos';
$labels['filenotfound']='Archivo no encontrado.';