<?php
# 
# This file is part of Roundcube "detach_attachments" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Détacher les attachements';
$labels['plugindescription']='Détacher les fichiers attachés à un email pour n\'envoyer qu\'un lien de téléchargement afin de réduire la taille de votre message. Les liens vers les fichiers détachés resteront valables 30 jours';
$labels['expires']='Le téléchargement a expiré';
$labels['deleteconfirmation']='Si vous continuez, le fichier attaché sera totalement supprimé du serveur. Voulez-vous continuer ?';
$labels['downloadquestion']='Voulez-vous télécharger le fichier attaché avant l\'effacement ?';
$labels['deletelink']='Supprimer le fichier attaché du serveur';
$labels['downloads']='Téléchargement(s)';
$labels['hint']='Le compteur de téléchargement indique combien de fois le(s) fichier(s) attaché(s) a (ont) été téléchargé(s). Si le fichier a été envoyé par erreur, veuillez l\'effacer pour prévenir d\'autre téléchargement.';
$labels['storeattachments']='Conserver les fichiers attachés sur le serveur';
$labels['cumsize']='Taille totale des fichiers attachés';
$labels['filenotfound']='Fichier non trouvé';