<?php
# 
# This file is part of Roundcube "detach_attachments" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Bijlagen loskoppelen';
$labels['plugindescription']='Koppel de bijlagen los van de email en stuur in plaats daarvan een download snelkoppeling. Er is wel een opmerking hierbij : Losgekoppelde bijlagen zijn maximaal 30 dagen beschikbaar.';
$labels['expires']='Download is verlopen';
$labels['deleteconfirmation']='Wanneer u doorgaat dan wordt de bijlage definitief verwijderd van de server. Wilt u doorgaan?';
$labels['downloadquestion']='Wilt u de bijlage binnenhalen voordat u hem verwijderd?';
$labels['deletelink']='Bijlage verwijderen van de server';
$labels['downloads']='Download(s)';
$labels['hint']='Deze downloadteller geeft aan hoeveel keer de bijlage is binnengehaald. Wanneer bijlages door een fout zijn verzonden, kun u beter de bijlage verwijderen om downloads te voorkomen.';
$labels['storeattachments']='Bijlages op de server laten staan';
$labels['cumsize']='Totale bijlage grootte';
$labels['filenotfound']='Bestand niet gevonden.';