<?php
# 
# This file is part of Roundcube "detach_attachments" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Odepnnij załączniki';
$labels['plugindescription']='Odepnij wychodzące załączniki wysyłając w zamian linka(URL). Linki będą miały ważność 30 dni.';
$labels['expires']='Link wygasł';
$labels['deleteconfirmation']='Jeżeli przejdziesz dalej, załączniki zostaną usuniete na stałe z serwera. Czy chcesz kontunuować?';
$labels['downloadquestion']='Czy chcesz pobrać załączniki przed skasowaniem?';
$labels['deletelink']='Skasuj załączniki z serwera';
$labels['downloads']='pobranie<small>(a)</small>';
$labels['hint']='Licznik pobrań pokazuje ile razy dany link został pobrany. <br /> Jeżeli załączniki były wysłane przez przypadek, skasuj je aby zablokować pobieranie.';
$labels['storeattachments']='Trzymaj załączniki na serwerze';
$labels['cumsize']='Rozmiar wszystkich załączników';
$labels['filenotfound']='Pliku nie znaleziono.';